os:
  - osx

language: python
python:
  - "3.6"
#virtualenv:
#  system_site_packages: true
before_install:
  - sudo apt-get install -y sox ffmpeg
addons:
  apt:
    update: true
install:
  - pip3 install -r requirements.txt
script:
  - python3 -m unittest discover -s tests.unit