language: python
python:
  - "3.6"
before_install:
  - sudo apt-get install -y sox ffmpeg
addons:
  apt:
    update: true
install:
  - pip install -r requirements.txt
script:
  - python -m unittest discover -s tests.unit